### PR TITLE
Add federal Bill Scraper back into OS

### PR DESCRIPTION
**Pull request by rmcarthur**
Creation of US as a "State", allowing US scraping to attach onto the jurisdiction.

### CODE REVIEW

**Comment by showerst** [comment]
I think your OCD division ID for the US is wrong, it should be ```ocd-division/country:us``` not ```ocd-jurisdiction/country:us/state:us```

**Comment by rmcarthur** [comment]
It seems like these are the only classification options: 
https://github.com/openstates/openstates-core/blob/main/openstates/data/common.py#L43
Can we add a country one?

**Comment by showerst** [comment]
ping @jamesturk -- I don't see why not. 

FWIW I'm running the shorter ID in the [US scrapers](https://github.com/openstates/openstates-scrapers/blob/main/scrapers/us/__init__.py#L9) that are in openstates-scrapers (just with --scrape to output JSON instead of saving the data) and it's not causing any problems with the output validation code.

**Comment by jamesturk** [comment]
Yes, it'd be OK to add country as a classification option to go forward with this.

I added a on the other commit about getting this merged- while I'm up for it, it'll have implications that'll need to be evaluated & require special casing within openstates.org most likely.

**Comment by rmcarthur** [comment]
That makes more sense. I'll clean it up so it's a `country` tag, and I'm also looking into getting the text extractor working for it as well.

**Comment by jamesturk** [comment]
thanks for this!  closing this in favor of #20 where I'm continuing this work with custom districts/etc. instead of relying on creation script (which doesn't really work well for the US special cases)

**Pull request closed without merging**
