### PR TITLE
Fixes for the admin UI. Improve support for legislation and org membership.

### PR DESCRIPTION
**Pull request by twentyforty**
Remove end_date VoteEventAdmin.
Fix the has_add_permission overrides. Admin works now.
Add some additional Inlines to extend support for Legislation.
Extend support for Organization membership and Posts.
Make readonly some fields that should be.
Improve ordering and search for several models.
Fix HTML rendering for certain fields by using format_html.

### CODE REVIEW

**Comment by twentyforty** [comment]
@jamesturk

**Comment by jamesturk** [comment]
Can you clarify what the purpose/use case is here so I can suggest some alternatives?

Editing in the admin is explicitly disabled as it is a bad idea generally.  I actually think we're more heading in the direction of dropping the admin altogether, but I'd love to understand what you're doing a bit better.

**Comment by twentyforty** [comment]
The purpose of the PR is to make the admin more navigable -- everything should remain read-only (Some fields were missed and they are now also readonly). It also surfaces more legislation and organizational information.

My vote would be to keep the admin UI. I personally really appreciate it as someone who is looking to get more familiar with the OCD spec. It is also a very nice tool to have to spot check data after imports. In my personal projects, I've found the django Admin UI to be pretty powerful considering its maintenance cost. Any particular reasons you are thinking about retiring it?

**Comment by jamesturk** [comment]
Gotcha, I did a quick skim & missed that.

I love the Django Admin generally, but the Django admin is quite slow at the scale we're working with now (a decade+ of bills/votes/etc.), and I think the project may be moving beyond it since it really is a read-only view for our purposes, but I'm fine to bring this in for now since that is a ways off.

There's also the US executives stuff, which I'm interested in supporting but haven't figured out if/where we'll need other changes to not make things blow up, could we split these apart?

**Comment by twentyforty** [comment]
Yes! Sorry about that. My changes in the client got picked up in the lint-fixing commit. I meant to send those to you after this PR. Files removed.

**Comment by jamesturk** [comment]
Thanks for that & for the contribution!  Sorry for the initial misread!

**Pull request merged**
