### PR TITLE
WIP: Upgrade Validation process

### PR DESCRIPTION
**Pull request by johnseekins**
Make sure that we require at least some keys when validating incoming objects.

This requires updating the JSONSchema version we're using and changing how we validate custom types.

### CODE REVIEW

**Comment by jamesturk** [comment]
Is there a reason that all fields aren't required anymore? Not sure what the context is here.

**Review by NewAgeAirbender — APPROVED** [review]

**Comment by johnseekins** [comment]
> Is there a reason that all fields aren't required anymore? Not sure what the context is here.
> 
> In the past we required every field to be present after a scrape to avoid dealing with edge cases, I assume at some point recently that was changed and this is re-adding specific fields to be required?

I have no idea, but these schemas had no required fields and I was just looking to add _any_.

**Comment by jessemortenson** [comment]
I'm not aware of any changes that got rid of required fields. I just started looking at this code for the first time in the last couple weeks. Glancing at the commit history for files in that folder (scrape/schema) it doesn't *seem* like there are commits removing requirements. Possible that I'm misunderstanding where required fields are asserted in the overall os-core scrape/update pipeline!

Part of what's going on here is that we want these schema to be a little portable, eg so that we can apply them to arbitrary JSON files and see if they validate. Rather than only applying them in the middle of the scrape/update pipeline to dicts that were just generated by a scrape. Not sure if that context helps.

**Review by jessemortenson — APPROVED** [review]
Overall LGTM, one more requirement on bill that I would add.

If you want to get more detailed there are some requirements we can add to sub entities of bill (I took a shot at it on that json-encoding of the schema I did), but that can also be subsequent work

**Pull request closed without merging**
